ModelLFSC: 1 #Flag to turn on or off Liquid Fuel modelling capabilities - 0 - No Liquid Fuels, 1 - Liquid Fuels Modeled
ModelSyntheticFuels: 1 #Flas to turn on or off Synthetic Fuel modeling

Liquid_Fuels_Regional_Demand: 0 #1: Regional resolution, 0: Global resolution for liquid fuels demand
Liquid_Fuels_Hourly_Demand: 1 #1: Hourly resolution, 0: Annual resolution for liquid fuels demand

#Conventional fuel shares in global percentage 
Conventional_Diesel_Share_Requirement: 0 # Specify Conventional Diesel Share ; 0 = not active; 1 = active systemwide
Conv_Diesel_Share: 0 # Enter a value between 0 and 1 to specify the fraction of systemwide conventional diesel

Conventional_Jetfuel_Share_Requirement: 0 # Specify Conventional Jetfuel Share ; 0 = not active; 1 = active systemwide
Conv_Jetfuel_Share: 0 # Enter a value between 0 and 1 to specify the fraction of systemwide conventional jetfuel

Conventional_Gasoline_Share_Requirement: 0 # Specify Conventional Gasoline Share ; 0 = not active; 1 = active systemwide
Conv_Gasoline_Share: 0 # Enter a value between 0 and 1 to specify the fraction of systemwide conventional gasoline

#Conventional fuels ratio, limit the ratio between conventional fuels purchase to represent fuel refinery
Conv_Jetfuel_to_Gasoline_ratio: 0 # Specify ratio of conventional Jetfuel to Gasoline
Conv_Jetfuel_to_Gasoline_Ratio_Min: 0.1451 #Min ratio
Conv_Jetfuel_to_Gasoline_Ratio_Max: 0.2033 #Max ratio

Conv_Diesel_to_Gasoline_ratio: 0 # Specify ratio of conventional Diesel to Gasoline
Conv_Diesel_to_Gasoline_Ratio_Min: 0.3492 #Min ratio
Conv_Diesel_to_Gasoline_Ratio_Max: 0.5147 #Max ratio

## Flexible allocation of liquid fuels (Fraction of Fuel A to Fuel B)
ModelFlexSyntheticFuels: 1

Max_Gasoline_To_Jetfuel_Frac: 0.25
Max_Gasoline_To_Diesel_Frac: 0.0000001

Max_Jetfuel_To_Gasoline_Frac: 0.25
Max_Jetfuel_To_Diesel_Frac: 0.25

Max_Diesel_To_Gasoline_Frac: 0.0000001
Max_Diesel_To_Jetfuel_Frac: 0.25
