ModelH2: 1 #Flag to turn or off Hydrogen Supply Chain modelling capabilities - 0 - no HSC, 1- HSC modeled
ModelH2G2P: 1 # Whether to model G2P in hydrogen supply chain - 0 - not included, 1 - included
H2PipeInteger: 0 # Whether to model pipeline capacity as discrete or integer - 0 - continuous capacity, 1- discrete capacity
ModelH2Pipelines: 1 # Whether to model pipeline in hydrogen supply chain - 0 - not included, 1 - included
ModelH2Trucks: 0 # Whether to model truck in hydrogen supply chain - 0 - not included, 1 - included
H2TrucksMaxDistance: 500 # the max number of miles or km for a truck route (depends on the units used throughout, calculated via time constraint based on truck speed)
ModelH2Liquid: 0 # Whether to model liquid demand and production - 0 - not included, 1 - included
H2GenCommit: 0 # Continuous or discrete capacity representation of H2 production technologies with unit commitment; 0 = modeled as continuous variables; 1 = modeled as integer variables;
H2NetworkExpansion: 1 # Transmission network expansional; 0 = not active; 1 = active systemwide
H2CO2Cap: 1 # CO2 emissions cap for HSC only; 0 = not active (no CO2 emission limit); 1 = mass-based emission limit constraint; 2 = load + rate-based emission limit constraint; 3 = generation + rate-based emission limit constraint; 4 = emissions penalized via a carbon price
H2G2PCommit: 0 #1 for unit commitment G2P representation, 0 continuous representation of H2 G2P tech
H2PipeDirection: 1

GreenH2ShareRequirement: 0 # Specify Green H2 share ; 0 = not active; 1 = active systemwide
GreenH2Share: 0.8 # Enter a value between 0 and 1 to specify the fraction of green H2 in systemwide annual H2 demand

